export function mock() {
    return [
        { value: "大饭店", address: "山东济南" },
        { value: "小饭店", address: "北京朝阳区" },
        { value: "豪华饭店", address: "上海黄浦区" },
        { value: "特色饭店", address: "广东深圳" },
        { value: "海鲜饭店", address: "福建厦门" },
        { value: "素食饭店", address: "四川成都" },
        { value: "火锅饭店", address: "重庆渝中区" },
        { value: "日本料理饭店", address: "东京市" },
        { value: "意大利饭店", address: "罗马市" },
        { value: "法国饭店", address: "巴黎市" },
        { value: "泰国饭店", address: "曼谷市" },
        { value: "韩国饭店", address: "首尔市" },
        { value: "墨西哥饭店", address: "墨西哥城" },
        { value: "阿根廷饭店", address: "布宜诺斯艾利斯" },
        { value: "印度饭店", address: "德里市" },
        { value: "巴西饭店", address: "里约热内卢" },
        { value: "埃及饭店", address: "开罗市" },
        { value: "摩洛哥饭店", address: "马拉喀什" },
        { value: "澳大利亚饭店", address: "悉尼市" },
        { value: "新西兰饭店", address: "奥克兰市" },
        { value: "南非饭店", address: "开普敦" },
        { value: "加拿大饭店", address: "多伦多市" },
        { value: "美国饭店", address: "纽约市" },
        { value: "墨尔本饭店", address: "墨尔本市" },
        { value: "奥地利饭店", address: "维也纳市" },
        { value: "荷兰饭店", address: "阿姆斯特丹" },
        { value: "瑞士饭店", address: "苏黎世" },
        { value: "瑞典饭店", address: "斯德哥尔摩" },
        { value: "丹麦饭店", address: "哥本哈根" },
        { value: "挪威饭店", address: "奥斯陆" },
        { value: "芬兰饭店", address: "赫尔辛基" }
    ];
}
